# Generated by Django 5.0 on 2023-12-07 18:03

import django.db.models.deletion
import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер ячейки')),
                ('description', models.CharField(max_length=250, verbose_name='Содержимое')),
                ('message_image', models.ImageField(upload_to='upload/', verbose_name='Баннер сообщении')),
                ('webapp_image', models.ImageField(upload_to='upload/', verbose_name='Фото миниапп')),
                ('content', djrichtextfield.models.RichTextField(max_length=4000)),
                ('open_date', models.DateField(verbose_name='Когда будет доступен')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='Ид в телеграмм')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=False)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cell', verbose_name='Ячейке')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tguser', verbose_name='Пользователь')),
            ],
        ),
    ]
