# Generated by Django 4.2.5 on 2023-12-12 08:22

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='additional_info',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=4000, null=True, verbose_name='Текст доп сообщении'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='content',
            field=djrichtextfield.models.RichTextField(max_length=1010, verbose_name='Текст под фото'),
        ),
    ]
