# Generated by Django 5.0 on 2023-12-08 06:27

import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_image', models.ImageField(upload_to='upload/', verbose_name='Баннер сообщении')),
                ('text', djrichtextfield.models.RichTextField(max_length=4000)),
                ('is_sent', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщении',
            },
        ),
    ]
