# Generated by Django 4.2.5 on 2023-12-13 08:04

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cell_additional_info_alter_cell_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedmessage',
            name='additional_info',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=4000, null=True, verbose_name='дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='plannedmessage',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='plannedmessage',
            name='send_time',
            field=models.DateTimeField(verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='plannedmessage',
            name='text',
            field=djrichtextfield.models.RichTextField(max_length=1010, verbose_name='Текст под баннер'),
        ),
    ]
