# Generated by Django 4.2.5 on 2023-12-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plannedmessage_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedmessage',
            name='message_image',
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.plannedmessage')),
            ],
        ),
    ]
