# Generated by Django 4.2.5 on 2023-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_plannedmessage_message_image_messageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageimage',
            options={'verbose_name': 'карточка сообщении', 'verbose_name_plural': 'карточки сообщении'},
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Ид в телеграмм'),
        ),
    ]
