# Generated by Django 4.2.5 on 2023-12-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_messageimage_options_alter_tguser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=None, editable=False, null=True, verbose_name='Дата создания')),
                ('planned_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plannedmessage', verbose_name='Сообщение')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tguser', verbose_name='Тг пользователь')),
            ],
        ),
    ]
